import { NextRequest } from "next/server";

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const text = String(body.text || "");

  // If external AI detector URL provided, proxy the request
  const detectorUrl = process.env.AI_DETECTOR_URL;
  const detectorKey = process.env.AI_DETECTOR_KEY;

  if (detectorUrl) {
    try {
      const res = await fetch(detectorUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(detectorKey ? { Authorization: `Bearer ${detectorKey}` } : {}),
        },
        body: JSON.stringify({ text }),
      });
      const json = await res.json();
      return new Response(JSON.stringify({ result: json.result ?? json }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    } catch (e) {
      return new Response(JSON.stringify({ result: "error" }), {
        status: 500,
        headers: { "Content-Type": "application/json" },
      });
    }
  }

  // Fallback: simple heuristic detection
  const heuristics = [
    /\bAs an AI\b/i,
    /\bAs an language model\b/i,
    /\bgenerated by\b/i,
    /\bThis content was generated\b/i,
  ];

  const isLikelyAI = heuristics.some((rx) => rx.test(text)) ||
    (text.split(" ").length > 200 && /\b\w+ing\b/.test(text));

  const result = isLikelyAI ? "ai" : "human";
  return new Response(JSON.stringify({ result }), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
}
