"use client";

import GlossyCard from "./GlossyCard";

const LETTERS = [
  { letter: "N", word: "Native", detail: "Built for real-world text, not lab benchmarks." },
  { letter: "A", word: "AI", detail: "Detects machine-generated patterns in any content." },
  { letter: "T", word: "Text", detail: "Analyzes writing style, tone, and structure." },
  { letter: "T", word: "Trust", detail: "Gives clear human vs. AI signals you can act on." },
  { letter: "E", word: "Evaluation", detail: "Scores content instantly with transparent results." },
  { letter: "S", word: "System", detail: "A complete detection stack — API, widget, and dashboard." },
];

export default function NattesSection() {
  const downloadWidget = () => {
    const link = document.createElement("a");
    link.href = "/widget/natte-widget.js";
    link.download = "natte-widget.js";
    link.click();
  };

  const downloadXEmbedGuide = () => {
    const origin = window.location.origin;
    const guide = [
      "# NATTES Widget — X Developer App Embed",
      "",
      "1. Register your app at https://developer.x.com/en/portal/dashboard",
      "2. Set callback URL: " + origin + "/api/connections/x/callback",
      "3. Add env vars: X_CLIENT_ID, X_CLIENT_SECRET, X_BEARER_TOKEN",
      "4. Connect your account at " + origin + "/dashboard",
      "",
      "## Basic embed",
      '<div data-natte-text="Post text here">',
      '  <div data-natte-widget></div>',
      "</div>",
      '<script src="' + origin + '/widget/natte-widget.js"></script>',
      "",
      "## X feed embed (uses your Developer App)",
      '<div data-natte-x-username="yourhandle" data-natte-x-count="10">',
      '  <div data-natte-widget></div>',
      "</div>",
      '<script src="' + origin + '/widget/natte-widget.js"></script>',
    ].join("\n");

    const blob = new Blob([guide], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "natte-x-widget-setup.md";
    link.click();
    URL.revokeObjectURL(url);
  };

  const openBrowserWidget = () => {
    window.open("/widget/demo.html", "_blank", "noopener,noreferrer");
  };

  return (
    <section className="mb-10 overflow-hidden rounded-[2rem] border border-white/10 bg-black/40 p-10 shadow-2xl backdrop-blur-md">
      <div className="flex flex-col gap-6 text-center sm:text-left">
        <span className="mx-auto inline-flex w-fit rounded-full border border-violet-500/30 bg-violet-500/10 px-4 py-1 text-sm font-semibold text-violet-300 sm:mx-0">
          NATTES
        </span>
        <div>
          <h2 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl">
            Native AI Text Trust Evaluation System
          </h2>
          <p className="mt-4 max-w-2xl text-base leading-7 text-white/50">
            NATTES is the engine behind Proof of Human — a framework for evaluating whether
            text was written by a person or generated by AI, wherever you read online.
          </p>
        </div>
      </div>

      <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {LETTERS.map((item) => (
          <GlossyCard key={`${item.letter}-${item.word}`}>
            <div className="flex items-start gap-3">
              <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-violet-400 to-violet-600 text-sm font-bold text-white">
                {item.letter}
              </span>
              <div>
                <h3 className="font-semibold text-white">{item.word}</h3>
                <p className="mt-1 text-sm leading-6 text-white/50">{item.detail}</p>
              </div>
            </div>
          </GlossyCard>
        ))}
      </div>

      <div className="mt-10 flex flex-col items-center gap-4 sm:flex-row sm:flex-wrap sm:justify-center">
        <button
          type="button"
          onClick={downloadWidget}
          className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/5 px-6 py-3 text-sm font-medium text-white transition hover:border-white/40 hover:bg-white/10"
        >
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
            <path
              d="M8 2v8M5 7l3 3 3-3M3 12h10"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
          Download widget locally
        </button>
        <button
          type="button"
          onClick={downloadXEmbedGuide}
          className="inline-flex items-center gap-2 rounded-full border border-violet-500/40 bg-violet-500/10 px-6 py-3 text-sm font-medium text-violet-300 transition hover:border-violet-500/60 hover:bg-violet-500/20"
        >
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
            <path
              d="M4 2h8l2 3v9H2V2h2z"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinejoin="round"
            />
            <path d="M6 7h4M6 10h4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
          </svg>
          X Developer App setup guide
        </button>
        <button
          type="button"
          onClick={openBrowserWidget}
          className="inline-flex items-center gap-2 rounded-full border border-sky-500/40 bg-sky-500/10 px-6 py-3 text-sm font-medium text-sky-300 transition hover:border-sky-500/60 hover:bg-sky-500/20"
        >
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
            <rect x="2" y="3" width="12" height="10" rx="1.5" stroke="currentColor" strokeWidth="1.5" />
            <path d="M2 5.5h12" stroke="currentColor" strokeWidth="1.5" />
          </svg>
          Use live widget in browser
        </button>
      </div>
    </section>
  );
}
